import Head from 'next/head'
import styles from '../styles/App.module.css'
import Link from 'next/link'

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>AirOne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/air.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/"><a>AirOne!</a></Link>
        </h1>

        <p className={styles.description}>
          Encontrá vuelos baratos desde tu origen{' '}
        
        </p>

        <Component {...pageProps} />
      </main>

    </div>
  )
}

export default MyApp
